apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-lb
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
