apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30080
      protocol: TCP
