kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "${CLUSTER_NAME}"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    # لمراقبة حالة الـ Nodes والـ Pods (Health & Resources)
    orchestratorExplorer:
      enabled: true
    # لمراقبة استهلاك الموارد (CPU/RAM)
    clusterChecks:
      enabled: true