apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: hello-app-tg-binding
  namespace: default
spec:
  serviceRef:
    name: hello-app       # اسم الـ Service
    port: 30080           # NodePort
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/nlb-tg-prod/abcd1234
  podSelector:
    matchLabels:
      app: hello-app
  networking:
    vpcID: vpc-xxxxxxxx    # optional لكن يُفضل تحديده
