apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: hello-app-tgb
spec:
  # الـ ARN بتاع التارجت جروب اللي الـ Terraform عمله للـ NLB
  targetGroupARN: ${{ needs.infra.outputs.NLB_TARGET_GROUP_ARN }} 
  targetType: ip # أو ip حسب إعدادات الـ TG في ترافورم
  serviceRef:
    name: hello-app # لازم يكون نفس اسم الـ Service اللي في Helm
    port: 80