apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: hello-app-tgb
  namespace: default
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:174508894676:targetgroup/nlb-tg-prod/622a3239db4896bb
  targetType: ip
  serviceRef:
    name: hello-app
    port: 80
