replicaCount: 2

image:
  repository: ""          # pipeline هيحطها
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: false           # لازم true عشان ALB controller يقرأه
  class: alb              # Ingress class
  scheme: internet-facing
  targetType: instance

aws:
  nlbName: ""             
  albControllerRoleArn: "" # pipeline يحط ARN للServiceAccount
