name: Infrastructure
on:
  workflow_call:
    inputs:
      terraform_action:
        required: true
        type: string
    outputs:
      EKS_CLUSTER:
        value: ${{ jobs.infra.outputs.EKS_CLUSTER }}
      ECR_REPO:
        value: ${{ jobs.infra.outputs.ECR_REPO }}

env:
  AWS_REGION: us-east-1
  TERRAFORM_DIR: ./terraform

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      EKS_CLUSTER: ${{ steps.set-outputs.outputs.EKS_CLUSTER }}
      ECR_REPO: ${{ steps.set-outputs.outputs.ECR_REPO }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Terraform Action
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform init -input=false
          if [ "${{ inputs.terraform_action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          elif [ "${{ inputs.terraform_action }}" == "apply" ]; then
            terraform apply -auto-approve
          else
            terraform plan
          fi

      - name: Set Outputs
        if: inputs.terraform_action == 'apply'
        id: set-outputs
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          echo "ECR_REPO=$(terraform output -raw repository_url)" >> $GITHUB_OUTPUT
          echo "EKS_CLUSTER=$(terraform output -raw eks_cluster_name)" >> $GITHUB_OUTPUT