name: Monitoring
on:
  workflow_call:
    inputs:
      eks_cluster:
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  datadog-setup:
    name: Datadog Installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Tools & Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ inputs.eks_cluster }}
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Datadog
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo update
          helm upgrade --install datadog-operator datadog/datadog-operator --namespace datadog --create-namespace --wait
          
          kubectl create secret generic datadog-secret \
            --from-literal api-key=$DD_API_KEY \
            --namespace datadog --dry-run=client -o yaml | kubectl apply -f -
          
          export CLUSTER_NAME=${{ inputs.eks_cluster }}
          envsubst < k8s/datadog-agent.yaml | kubectl apply -n datadog -f -